#!/usr/bin/env node
/**
 * @fileoverview Standalone Analysis Script.
 * Runs a complete AI-powered analysis pipeline: failure patterns, coverage/fragility,
 * and test suggestions. Outputs a consolidated Markdown report.
 *
 * Usage:
 * ```bash
 * npx ts-node analyze.ts
 * ```
 */
import fs from 'fs';
import path from 'path';
import { AIProviderFactory } from './src/analyzer/ai-client';
import { PROMPTS } from './src/analyzer/prompts';
import process from 'process';

/** Absolute path to the storage directory where context and maps are kept. */
const STORAGE_DIR = path.resolve(__dirname, '../storage');
/** Path to the failure context Markdown file generated by the reporter. */
const CONTEXT_FILE = path.join(STORAGE_DIR, 'context.md');
/** Path to the system-map JSON file generated by the reporter. */
const MAP_FILE = path.join(STORAGE_DIR, 'system-map.json');
/** Directory where timestamped analysis reports are saved. */
const REPORTS_DIR = path.join(STORAGE_DIR, 'reports');

/**
 * Executes the full analysis pipeline.
 *
 * Steps:
 * 1. Validates that `context.md` and `system-map.json` exist.
 * 2. Analyzes failure patterns (if any failures are recorded).
 * 3. Analyzes coverage and fragility across all mapped routes.
 * 4. Suggests new tests for routes with low coverage (score < 60).
 * 5. Writes a consolidated Markdown report to `storage/reports/`.
 *
 * @throws {Error} If required data files are missing or the AI provider is unreachable.
 */
async function analyze() {
  console.log('\n🔍 Playwright Intelligence — Análise iniciada\n');

  // Validações
  if (!fs.existsSync(CONTEXT_FILE)) {
    console.error('❌ context.md não encontrado. Rode os testes primeiro.');
    process.exit(1);
  }
  if (!fs.existsSync(MAP_FILE)) {
    console.error('❌ system-map.json não encontrado. Rode os testes primeiro.');
    process.exit(1);
  }

  const systemMapContent = fs.readFileSync(MAP_FILE, 'utf-8');
  const systemMap = JSON.parse(systemMapContent);

  if (systemMap.totalRoutes === 0) {
    console.warn('⚠️  Aviso: Nenhuma rota mapeada no system-map.json. A análise de cobertura será limitada.');
  }
  const context = fs.readFileSync(CONTEXT_FILE, 'utf-8');
  const ai = AIProviderFactory.create();

  const provider = process.env.AI_PROVIDER ?? 'ollama';
  const model = process.env.OLLAMA_MODEL ?? 'gemma4:e2b';
  console.log(`🤖 Provider: ${provider}${provider === 'ollama' ? ` (${model})` : ''}\n`);

  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const reportFile = path.join(REPORTS_DIR, `report-${timestamp}.md`);

  let report = `# Playwright Intelligence Report\n_Gerado em ${new Date().toLocaleString('pt-BR')}_\n\n`;

  // ── 1. Análise de falhas ─────────────────────────────────
  const hasFailures = context.includes('## FAILURE');

  if (hasFailures) {
    // Extrai screenshots e realiza análise visual antes da análise de padrões
    const enrichedContext = await enrichContextWithVision(context, ai);
    
    process.stdout.write('📋 Analisando padrões de falha (texto + visão)...');
    const failureAnalysis = await ai.analyze(PROMPTS.analyzeFailures, enrichedContext);
    process.stdout.write(' ✅\n');
    report += `# Análise de Falhas\n\n${failureAnalysis}\n\n---\n\n`;
  } else {
    console.log('✅ Nenhuma falha registrada no context.md');
    report += `# Análise de Falhas\n\n✅ Nenhuma falha registrada.\n\n---\n\n`;
  }

  // ── 2. Fragilidade e cobertura ───────────────────────────
  process.stdout.write('🗺️  Analisando cobertura e fragilidade...');
  const fragilityAnalysis = await ai.analyze(PROMPTS.identifyFragility, systemMapContent);
  process.stdout.write(' ✅\n');
  report += `# Cobertura e Fragilidade\n\n${fragilityAnalysis}\n\n---\n\n`;

  // ── 3. Sugestão de novos testes ──────────────────────────
  const lowCoverageRoutes = getLowCoverageRoutes(systemMapContent);

  if (lowCoverageRoutes.length > 0) {
    process.stdout.write(`🧪 Sugerindo testes para ${lowCoverageRoutes.length} rota(s) com baixa cobertura...`);
    const suggestions = await ai.analyze(PROMPTS.suggestTests, systemMapContent);
    process.stdout.write(' ✅\n');
    report += `# Sugestões de Novos Testes\n\n${suggestions}\n\n---\n\n`;
  } else {
    console.log('✅ Todas as rotas com cobertura adequada.');
  }

  // ── Salva relatório ──────────────────────────────────────
  fs.writeFileSync(reportFile, report);
  console.log(`\n✨ Relatório salvo em: ${reportFile}\n`);
}

/**
 * Parses context.md, finds screenshots, and adds AI-generated visual descriptions.
 */
async function enrichContextWithVision(context: string, ai: any): Promise<string> {
  if (!ai.analyzeImage) return context;

  const failureBlocks = context.split('## FAILURE').filter(b => b.trim());
  let enrichedContext = '# Playwright Intelligence — Enriched Context\n\n';

  for (const block of failureBlocks) {
    const fullBlock = `## FAILURE${block}`;
    
    // Procura por Markdown de imagem: ![failure-X](path)
    const screenshotMatch = block.match(/!\[failure-\d+\]\((.*?)\)/);
    
    if (screenshotMatch && screenshotMatch[1]) {
      const screenshotPath = screenshotMatch[1];
      
      if (fs.existsSync(screenshotPath)) {
        process.stdout.write(`🖼️  Analisando visualmente FAILURE #${extractId(block)}...`);
        try {
          const visualAnalysis = await ai.analyzeImage(screenshotPath, PROMPTS.analyzeScreenshot);
          const enrichedBlock = fullBlock.replace(
            '---', 
            `### Análise Visual (Gemma 4 Vision)\n${visualAnalysis}\n\n---`
          );
          enrichedContext += enrichedBlock;
          process.stdout.write(' ✅\n');
        } catch (err) {
          process.stdout.write(' ❌ (erro na visão)\n');
          enrichedContext += fullBlock;
        }
      } else {
        enrichedContext += fullBlock;
      }
    } else {
      enrichedContext += fullBlock;
    }
  }

  return enrichedContext;
}

/** Extracts failure ID from block header */
function extractId(block: string): string {
  const match = block.match(/#(\d+)/);
  return match ? match[1] : '?';
}

/**
 * Parses the system-map JSON and returns routes whose coverage score is below 60.
 *
 * @param mapJson - The raw JSON string of the system-map file.
 * @returns An array of route paths with low coverage, or an empty array on parse failure.
 */
function getLowCoverageRoutes(mapJson: string): string[] {
  try {
    const map = JSON.parse(mapJson);
    return Object.entries(map.coverage ?? {})
      .filter(([, v]: [string, any]) => v.score < 60)
      .map(([route]) => route);
  } catch {
    return [];
  }
}

analyze().catch((err) => {
  console.error('\n❌ Erro durante análise:', err.message);
  if (err.message.includes('ECONNREFUSED') || err.message.includes('fetch')) {
    console.error('\nDica: Verifique se o Ollama está rodando: ollama serve');
  }
  process.exit(1);
});
