services:
  ollama:
    image: ollama/ollama:latest
    container_name: playwright-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS="*"
      - OLLAMA_CONTEXT_LENGTH=8192
      # A MÁGICA: Ativa o motor Vulkan
      #- OLLAMA_VULKAN=1

      # Precisamos devolver o acesso físico da placa gráfica para o Vulkan enxergar
    devices:
      - /dev/dri:/dev/dri

    restart: unless-stopped
    network_mode: bridge
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama_data:
    driver: local
